name: rest2-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy>=1.21.0
  - scipy>=1.7.0
  - pyyaml>=6.0
  - pip
  - pip:
    - MDAnalysis>=2.0.0
    - MDAnalysisTests>=2.0.0
    - matplotlib>=3.5.0
    - seaborn>=0.11.0
    - jupyter>=1.0.0
    - ipykernel>=6.0.0
    - pytest>=6.0.0
    - pytest-cov>=3.0.0
    - black>=22.0.0
    - flake8>=4.0.0 